version: '3'

services:
  flasksrv:
    build:
      context: ./flasksrv
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - /mnt/sda/mc:/data

  jellyfin:
    build:
      context: ./jellyfin
      dockerfile: Dockerfile
    volumes:
      - "/mnt/sda/media:/media"
    ports:
      - "8096:8096"
